version: '3'
services:
  app:
    image: chatgpt-app
    ports:
      - "80:8501"
      - "443:8501"
      - "8501:8501"
    volumes:
      - ../:/app/
      - ~/.config/gcloud/:/root/.config/gcloud/
    env_file:
      - .env
